name: stub

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  stub-32:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: stub
