name: testing

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Set output, exit 0
        id: run-tests-0
        shell: bash
        run: |
          test_type=unit_test
          echo "test_type=$test_type" >> $GITHUB_OUTPUT
          exit 0
      - name: Set output, exit 1
        id: run-tests-1
        shell: bash
        run: |
          test_type=unit_test
          echo "test_type=$test_type" >> $GITHUB_OUTPUT
          exit 1

      - name: Print outputs
        if: always()
        shell: bash
        run: |
          echo "'run-tests-0' always: ${{ steps.run-tests-0.outputs.test_type }}"
          echo "'run-tests-1' always: ${{ steps.run-tests-1.outputs.test_type }}"

      - name: Gated by output of 'run-tests-0' no curlies
        if: steps.run-tests-0.outputs.test_type == 'unit_test'
        shell: bash
        run: |
          echo "'run-tests-0' no curlies: ${{ steps.run-tests-0.outputs.test_type }}"

      - name: Gated by output of 'run-tests-1' no curlies
        if: steps.run-tests-1.outputs.test_type == 'unit_test'
        shell: bash
        run: |
          echo "'run-tests-1' no curlies: ${{ steps.run-tests-1.outputs.test_type }}"

      - name: Gated by output of 'run-tests-0' with curlies
        if: ${{ steps.run-tests-0.outputs.test_type == 'unit_test'  }}
        shell: bash
        run: |
          echo "'run-tests-0' with curlies: ${{ steps.run-tests-0.outputs.test_type }}"

      - name: Gated by output of 'run-tests-1' with curlies
        if: ${{ steps.run-tests-1.outputs.test_type == 'unit_test' }}
        shell: bash
        run: |
          echo "'run-tests-1' with curlies: ${{ steps.run-tests-1.outputs.test_type }}"
